### ISSUE TITLE
マッチング開始 / マッチング完了 を実装する

### ISSUE THREAD

**Issue by yurafuca** [best-summer/project-dystopia#3]
ランダムマッチングにするので `ルーム作成` を廃止して`マッチング開始` / `マッチング完了` を実装する．
マッチング完了時には相手の戦績情報を response に含める．

**Comment by yurafuca** [comment]
マッチング完了時に WebSocket サーバ は，戦績情報にくわえて room_id を返却する．以降クライアントは room_id を Request Body に含めてサーバと通信する．

**Comment by garicchi** [comment]
fixしました
#4

**Comment by yurafuca** [comment]
Merged.
